let images=[
    {category:"Abstract", src:"../../../images/categories/abstract2.jpg"},
    {category:"Adventure", src:"../../../images/categories/adventure.jpg"},
    {category:"Animals", src:"../../../images/categories/animals.jpg"},
    {category:"Bluffing", src:"../../../images/categories/bluffing.jpg"},
    {category:"Card Game", src:"../../../images/categories/cardgame.jpg"},
    {category:"City Building", src:"../../../images/categories/citybuilding1.jpg"},
    {category:"Cooperative", src:"../../../images/categories/cooperativegames1.jpg"},
    {category:"Deduction", src:"../../../images/categories/deduction2.jpg"},
    {category:"Dice", src:"../../../images/categories/dice.jpg"},
    {category:"Educational", src:"../../../images/categories/educational1.jpg"},
    {category:"Family Game", src:"../../../images/categories/family2.jpg"},
    {category:"Farming", src:"../../../images/categories/farming.png"},
    {category:"Horror", src:"../../../images/categories/horror.jpg"},
    {category:"Humor", src:"../../../images/categories/humor.jpg"},
    {category:"Medieval", src:"../../../images/categories/medieval.jpg"},
    {category:"Memory", src:"../../../images/categories/memory2.jpg"},
    {category:"Mythology", src:"../../../images/categories/mythology2.jpg"},
    {category:"Party Game", src:"../../../images/categories/party2.jpg"},
    {category:"Puzzle", src:"../../../images/categories/puzzle.jpg"},
    {category:"RPG", src:"../../../images/categories/rpg.jpg"},
    {category:"Sci-Fi", src:"../../../images/categories/scifi2.jpg"},
    {category:"Strategy", src:"../../../images/categories/strategy.jpg"},
    {category:"Wargame", src:"../../../images/categories/wargame.jpg"},
    {category:"Western", src:"../../../images/categories/western.jpg"},
    {category:"Zombies", src:"../../../images/categories/zombies.jpg"},
]

export default images
